### ISSUE TITLE
Preparations for B13.1 Registry Updates

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#143]
## 💡 Description

- [x] Prepare upgrade plan for upgrading existing services
- [x] Identify updates to registry schemas
- [x] Identify updates to loader tools that could impact metadata
- [x] Develop script(s) to support updates

## Scripts needed
- [ ] ~Script for migrating `String` fields to `arrays` in registry per https://github.com/NASA-PDS/registry-common/issues/29~

**Comment by jordanpadams** [comment]
📆 April status: Work in progress identifying upgrade needs for operational registries. On schedule

**Comment by jordanpadams** [comment]
All sub-tasks completed. Descoping `Script for migrating String fields to arrays in registry per https://github.com/NASA-PDS/registry-common/issues/29` until it is determined to be an issue with the API or from the end user
