### ISSUE TITLE
Preparations to Support B13.0 Registry Upgrades

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#46]
## 💡 Description

- [x] Prepare upgrade plan for upgrading existing services
- [x] Identify updates to registry schemas
- [x] Identify updates to loader tools that could impact metadata
- [x] Develop script(s) to support updates

Tickets to consider:
NASA-PDS/registry-mgr#53
